title: Content
description: A CakePHP 3.x plugin for Content Management System backend in Bootstrap style
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
