site_name: Content Docs
site_url: http://www.aoliverio.com
site_description: Content Management System backend, is a Builder extension.
site_author: Antonio Oliverio

repo_url: https://github.com/aoliverio/content/

pages:
- Home: index.md
- Preface:
    - Overview: overview.md
- Getting started:
    - Installation: installation.md
    - Configuration: configuration.md
- DEVELOPERS:
    - Configure: Developers/content-configure.md
    - Sessions: Developers/content-sessions.md