-- MySQL Script generated by MySQL Workbench
-- Fri Apr  1 12:49:18 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema unicz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `cms_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_contents` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) NOT NULL DEFAULT '0',
  `name` VARCHAR(255) NOT NULL,
  `content_title` VARCHAR(255) NOT NULL,
  `content_description` LONGTEXT NOT NULL,
  `content_excerpt` TEXT NOT NULL,
  `content_deadline` DATETIME NOT NULL,
  `content_password` VARCHAR(55) NOT NULL,
  `content_status` VARCHAR(55) NOT NULL,
  `content_path` VARCHAR(255) NOT NULL,
  `content_type` VARCHAR(55) NOT NULL,
  `content_mime_type` VARCHAR(255) NOT NULL,
  `publish_start` DATETIME NOT NULL,
  `publish_end` DATETIME NOT NULL,
  `author_id` INT(11) NOT NULL DEFAULT '0',
  `menu_order` INT(11) NOT NULL DEFAULT '0',
  `created` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `modified` DATETIME NOT NULL,
  `modified_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 49680
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cms_content_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_content_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_id` BIGINT(20) NOT NULL,
  `role_id` BIGINT(20) NOT NULL DEFAULT 0,
  `user_id` BIGINT(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_cms_contents_idx` (`content_id` ASC),
  CONSTRAINT `fk_cms_contents`
    FOREIGN KEY (`content_id`)
    REFERENCES `unicz`.`cms_contents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cms_content_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_content_meta` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content_id` BIGINT(20) NOT NULL,
  `meta_key` VARCHAR(255) NOT NULL,
  `meta_value` LONGTEXT NOT NULL,
  `menu_order` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_cms_contents2_idx` (`content_id` ASC),
  CONSTRAINT `fk_cms_contents2`
    FOREIGN KEY (`content_id`)
    REFERENCES `cms_contents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cms_terms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_terms` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cms_term_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_term_permissions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `term_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) NOT NULL DEFAULT '0',
  `role_id` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_cms_terms_idx` (`term_id` ASC),
  CONSTRAINT `fk_cms_terms`
    FOREIGN KEY (`term_id`)
    REFERENCES `cms_terms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 169
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cms_term_taxonomy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_term_taxonomy` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
  `term_id` BIGINT(20) UNSIGNED NOT NULL,
  `taxonomy` VARCHAR(32) NOT NULL DEFAULT '',
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `count` BIGINT(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `parent_id` (`parent_id` ASC),
  INDEX `taxonomy` (`taxonomy` ASC),
  INDEX `fk_cms_terms1_idx` (`term_id` ASC),
  CONSTRAINT `fk_cms_terms1`
    FOREIGN KEY (`term_id`)
    REFERENCES `cms_terms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 55
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `cms_term_relationships`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cms_term_relationships` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content_id` BIGINT(20) NOT NULL,
  `term_taxonomy_id` BIGINT(20) UNSIGNED NOT NULL,
  `menu_order` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fk_cms_contents1_idx` (`content_id` ASC),
  INDEX `fk_cms_term_taxonomy1_idx` (`term_taxonomy_id` ASC),
  CONSTRAINT `fk_cms_contents1`
    FOREIGN KEY (`content_id`)
    REFERENCES `cms_contents` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cms_term_taxonomy1`
    FOREIGN KEY (`term_taxonomy_id`)
    REFERENCES `cms_term_taxonomy` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 31604
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
